// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edoenkwbybsngxpebpkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkb2Vua3dieWJzbmd4cGVicGtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTMyMjEsImV4cCI6MjA2NzEyOTIyMX0.YveTuQN0D7S0fjxDd1vtSEbYvz-k0p_rpBmJB4MXiKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});